### ISSUE TITLE
DllNotFoundException problem for DynamicLua

### ISSUE THREAD

**Issue by oslvbo** [nrother/dynamiclua#11]
I find DynamicLua in NuGet, all of it's features are just what I want. Great work, nrother! Thanks for it!

Now, let me just post my problem below:

I was developing my new application on mono framework, but I can't even using it in the start time. When I was coding like this:

```
dynamic luaBase = new DynamicLua.DynamicLua();
```

The error message would say It missed some dll like this:

```
System.DllNotFoundException : lua52, KeraLua
```

But even I install NLua and KeraLua from NuGet, Error still appears, with saying "DllNotFound". What should I do? Is it that DynamicLua doesn't support non-Windows platform or just a stupid mistake cause by my wrong setting?

**Comment by nrother** [comment]
Yes, in the `lua52.dll` is embedded in the DynamicLua (and unpacked at runtime), but this file is a native Windows DLL. _So no support for Mono currently..._

If you like, you can try [KopiLua](https://github.com/NLua/KopiLua), that is a pure C# implementation of Lua, and should run on Mono. You should be able to recompile DynamicLua using KopiLua.

Please note that there are some post build events in the sln-file which pack everything into one DLL. You might need to remove them.

If I'll find some time I might upload a build file for DynamicLua bundled with KopiLua...

**Comment by oslvbo** [comment]
That's nice, I will try it! Thanks!

**Comment by nrother** [comment]
I just pushed a branch named `kopilua`, this contains a `NLua.dll` build against KopiLua, so this build should run on Mono :smile:  Here is a download for the build DLL: http://www.file-upload.net/download-8701802/DynamicLua.dll.html

I just tested it on Windows, but KopiLua should run on Mono (even Android/iOS), according to their documentation.

**Comment by oslvbo** [comment]
It works! Thanks for your work!!

**Comment by d-led** [comment]
I wanted to suggest the same. Niklas, do you think, that would be possible to create a single branch containing all three backends, with the motivation that the nuget will work on mono too?

**Comment by nrother** [comment]
I don't now so much about NuGet, but it could be possible.

I'll look into it, when I'm back from vacation (in about 3 weeks...)

**Comment by d-led** [comment]
:+1:
